// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhpj_35kFDsuWrjhH0BBn7ewCz2wGKhqA',
    appId: '1:454297523565:web:f74f1db3024d8b6555b664',
    messagingSenderId: '454297523565',
    projectId: 'bismillah-f5675',
    authDomain: 'bismillah-f5675.firebaseapp.com',
    databaseURL: 'https://bismillah-f5675-default-rtdb.firebaseio.com',
    storageBucket: 'bismillah-f5675.appspot.com',
    measurementId: 'G-STRYNQD7KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbbr0FRtYxYTrQodDf4ti_7M6rLRjCT7A',
    appId: '1:454297523565:android:12a356a935a2285755b664',
    messagingSenderId: '454297523565',
    projectId: 'bismillah-f5675',
    databaseURL: 'https://bismillah-f5675-default-rtdb.firebaseio.com',
    storageBucket: 'bismillah-f5675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEvYWOtEGPQg_ytCTpqkmf_SxCaTRUOnA',
    appId: '1:454297523565:ios:7881e1ea64f8032e55b664',
    messagingSenderId: '454297523565',
    projectId: 'bismillah-f5675',
    databaseURL: 'https://bismillah-f5675-default-rtdb.firebaseio.com',
    storageBucket: 'bismillah-f5675.appspot.com',
    iosBundleId: 'com.example.bismillah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEvYWOtEGPQg_ytCTpqkmf_SxCaTRUOnA',
    appId: '1:454297523565:ios:ba5cba423d8c9c3955b664',
    messagingSenderId: '454297523565',
    projectId: 'bismillah-f5675',
    databaseURL: 'https://bismillah-f5675-default-rtdb.firebaseio.com',
    storageBucket: 'bismillah-f5675.appspot.com',
    iosBundleId: 'com.example.bismillah.RunnerTests',
  );
}
